---
services:
  - docker

before_install:
  - docker build . --file Dockerfile --tag ceph-pulpito-test
  - docker run -d -p 80:8080 ceph-pulpito-test
  - sleep 4
script:
  - docker ps -a | grep ceph-pulpito-test
